name: flutter_examples
description: "An example Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  app_common:
    path: packages/app_common
  dio: ^5.2.0
  feature_payment_history:
    path: packages/feature_payment_history
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  get_it: ^7.7.0
  go_router: ^14.2.0
  localization:
    path: packages/localization
  network:
    path: packages/network
  provider: ^6.1.2

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  build_runner: '^2.1.4'
  flutter_test:
    sdk: flutter
  json_serializable: '^6.1.4'
  pubspec_dependency_sorter: '^1.0.5'

flutter:
  uses-material-design: true
  assets:
    - assets/
