name: network
description: Bundle of request/response models
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  collection: ^1.15.0
  dio: ^5.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.9.0
  retrofit: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.2.2
  freezed: ^2.0.3+1
  json_serializable: ^6.1.5
  retrofit_generator: ^8.0.0
