name: localization
description: "Localizations package of the examples app"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.19.0"

dependency_overrides:
  intl: ^0.19.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:

flutter:
  generate: true

dev_dependencies:
  dependency_validator: ^3.2.2
